/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Info */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin-only": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Only Endpoint */
        get: operations["admin_only_endpoint_api_v1_auth_admin_only_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pm-or-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pm Or Admin Endpoint */
        get: operations["pm_or_admin_endpoint_api_v1_auth_pm_or_admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget Vs Actual */
        get: operations["get_budget_vs_actual_api_v1_projects__project_id__budget_get"];
        put?: never;
        /** Set Budget */
        post: operations["set_budget_api_v1_projects__project_id__budget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budgets */
        get: operations["get_budgets_api_v1_projects__project_id__budgets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expenses */
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expense */
        get: operations["get_expense_api_v1_expenses__expense_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Expense */
        patch: operations["update_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Expense */
        post: operations["transition_expense_api_v1_expenses__expense_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Evidence
         * @description Upload evidence file for an expense.
         */
        post: operations["upload_evidence_api_v1_evidence_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Get evidence by ID.
         */
        get: operations["get_evidence_api_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Evidence
         * @description Delete evidence file.
         */
        delete: operations["delete_evidence_api_v1_evidence__evidence_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/expense/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evidence By Expense
         * @description List evidence files for an expense.
         */
        get: operations["list_evidence_by_expense_api_v1_evidence_expense__expense_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Presigned Url
         * @description Generate presigned URL for evidence access.
         */
        post: operations["get_presigned_url_api_v1_evidence_presigned_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ocr/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Ocr Processing
         * @description Start OCR processing on an evidence file.
         */
        post: operations["start_ocr_processing_api_v1_ocr_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ocr/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ocr Job
         * @description Get OCR job status and results.
         */
        get: operations["get_ocr_job_api_v1_ocr_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Ocr Job
         * @description Delete an OCR job and its attempts.
         */
        delete: operations["delete_ocr_job_api_v1_ocr_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ocr/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ocr Jobs
         * @description List OCR processing jobs.
         */
        get: operations["list_ocr_jobs_api_v1_ocr_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ocr/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Ocr Job
         * @description Retry a failed OCR job.
         */
        post: operations["retry_ocr_job_api_v1_ocr_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Extraction
         * @description Start LLM extraction on evidence (requires completed OCR).
         */
        post: operations["start_extraction_api_v1_extraction_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/process-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Sync
         * @description Run LLM extraction synchronously (for testing/small texts).
         */
        post: operations["extract_sync_api_v1_extraction_process_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Extraction Job
         * @description Get extraction job status and results.
         */
        get: operations["get_extraction_job_api_v1_extraction_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Extraction Job
         * @description Delete an extraction job.
         */
        delete: operations["delete_extraction_job_api_v1_extraction_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Extraction Jobs
         * @description List LLM extraction jobs.
         */
        get: operations["list_extraction_jobs_api_v1_extraction_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Extraction Job
         * @description Retry a failed extraction job.
         */
        post: operations["retry_extraction_job_api_v1_extraction_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Extraction
         * @description Validate extraction result and get confidence adjustment.
         */
        post: operations["validate_extraction_api_v1_extraction_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staging/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage Expenses
         * @description Stage expenses for human review.
         */
        post: operations["stage_expenses_api_v1_staging_stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staging/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Staged Expenses
         * @description List staged expenses with pagination.
         */
        get: operations["list_staged_expenses_api_v1_staging_expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staging/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Staged Expense
         * @description Get detailed staged expense for review.
         */
        get: operations["get_staged_expense_api_v1_staging_expenses__expense_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staging/expenses/{expense_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Stage Action
         * @description Approve, reject, or request changes for a staged expense.
         */
        post: operations["take_stage_action_api_v1_staging_expenses__expense_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staging/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Staging Stats
         * @description Get staging statistics.
         */
        get: operations["get_staging_stats_api_v1_staging_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_evidence_api_v1_evidence_upload_post */
        Body_upload_evidence_api_v1_evidence_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Metadata */
            metadata?: Record<string, never> | null;
        };
        /** BudgetCreate */
        BudgetCreate: {
            /** Amount */
            amount: number;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Category Id */
            category_id?: string | null;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
        };
        /** BudgetVsActualResponse */
        BudgetVsActualResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Total Budget */
            total_budget: number;
            /** Total Actual */
            total_actual: number;
            /** Remaining */
            remaining: number;
            /** By Category */
            by_category: Record<string, never>[];
            /**
             * Currency
             * @default INR
             */
            currency: string;
        };
        /**
         * EvidenceListResponse
         * @description Paginated evidence list response.
         */
        EvidenceListResponse: {
            /** Items */
            items: components["schemas"]["EvidenceResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * EvidenceResponse
         * @description Evidence file response.
         */
        EvidenceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /** Object Name */
            object_name: string;
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type: string;
            /** Size */
            size: number;
            /** Checksum */
            checksum: string;
            /** Metadata */
            metadata: Record<string, never> | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EvidenceUploadResponse
         * @description Response after evidence upload.
         */
        EvidenceUploadResponse: {
            /** Object Name */
            object_name: string;
            /** Checksum */
            checksum: string;
            /** Size */
            size: number;
            /** Content Type */
            content_type: string;
            /** Presigned Url */
            presigned_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ExpenseCreate */
        ExpenseCreate: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
            /** Subtotal */
            subtotal: number | string;
            /** Tax Amount */
            tax_amount: number | string;
            /** Total */
            total: number | string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /**
             * Payment Method
             * @default CASH
             */
            payment_method: string;
            /** Vendor Id */
            vendor_id?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["ExpenseLineItemCreate"][] | null;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Gstin Supplier */
            gstin_supplier?: string | null;
            /** Hsn Sac Code */
            hsn_sac_code?: string | null;
            /** Cgst Amount */
            cgst_amount?: number | string | null;
            /** Sgst Amount */
            sgst_amount?: number | string | null;
            /** Igst Amount */
            igst_amount?: number | string | null;
            /** Irn */
            irn?: string | null;
        };
        /** ExpenseLineItemCreate */
        ExpenseLineItemCreate: {
            /** Description */
            description: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit Price */
            unit_price?: number | string | null;
            /** Amount */
            amount: number | string;
            /** Tax Amount */
            tax_amount?: number | string | null;
        };
        /** ExpenseLineItemResponse */
        ExpenseLineItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Description */
            description: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit Price */
            unit_price?: string | null;
            /** Amount */
            amount: string;
            /** Tax Amount */
            tax_amount?: string | null;
        };
        /** ExpenseListResponse */
        ExpenseListResponse: {
            /** Items */
            items: components["schemas"]["ExpenseResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ExpenseResponse */
        ExpenseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Source Event Id */
            source_event_id: string | null;
            /** Vendor Id */
            vendor_id: string | null;
            /** Category Id */
            category_id: string | null;
            /** Transaction Date */
            transaction_date: string;
            /** Subtotal */
            subtotal: string;
            /** Tax Amount */
            tax_amount: string;
            /** Total */
            total: string;
            /** Currency */
            currency: string;
            /** Payment Method */
            payment_method: string;
            /** Gstin Supplier */
            gstin_supplier: string | null;
            /** Hsn Sac Code */
            hsn_sac_code: string | null;
            /** Cgst Amount */
            cgst_amount: string | null;
            /** Sgst Amount */
            sgst_amount: string | null;
            /** Igst Amount */
            igst_amount: string | null;
            /** Irn */
            irn: string | null;
            /** Confidence Score */
            confidence_score: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Receipt Id */
            receipt_id: string | null;
            /** Source Audit Event Id */
            source_audit_event_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
            vendor?: components["schemas"]["VendorResponse"] | null;
            /**
             * Line Items
             * @default []
             */
            line_items: components["schemas"]["ExpenseLineItemResponse"][];
        };
        /** ExpenseTransitionRequest */
        ExpenseTransitionRequest: {
            /** New Status */
            new_status: string;
        };
        /** ExpenseUpdate */
        ExpenseUpdate: {
            /** Transaction Date */
            transaction_date?: string | null;
            /** Subtotal */
            subtotal?: number | string | null;
            /** Tax Amount */
            tax_amount?: number | string | null;
            /** Total */
            total?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Payment Method */
            payment_method?: string | null;
            /** Vendor Id */
            vendor_id?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Gstin Supplier */
            gstin_supplier?: string | null;
            /** Hsn Sac Code */
            hsn_sac_code?: string | null;
            /** Cgst Amount */
            cgst_amount?: number | string | null;
            /** Sgst Amount */
            sgst_amount?: number | string | null;
            /** Igst Amount */
            igst_amount?: number | string | null;
            /** Irn */
            irn?: string | null;
            /** Lifecycle Status */
            lifecycle_status?: string | null;
        };
        /**
         * ExtractionJobListResponse
         * @description Paginated extraction job list.
         */
        ExtractionJobListResponse: {
            /** Items */
            items: components["schemas"]["ExtractionJobStatus"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ExtractionJobStatus
         * @description Extraction job status.
         */
        ExtractionJobStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Event Id */
            source_event_id: string | null;
            /** Status */
            status: string;
            result: components["schemas"]["ExtractionResponse"] | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * ExtractionProcessResponse
         * @description Response after starting extraction.
         */
        ExtractionProcessResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * ExtractionRequest
         * @description Request to run LLM extraction.
         */
        ExtractionRequest: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Provider */
            provider?: string | null;
            /**
             * Use Cached Ocr
             * @default true
             */
            use_cached_ocr: boolean;
        };
        /**
         * ExtractionResponse
         * @description LLM extraction result.
         */
        ExtractionResponse: {
            /** Vendor Name */
            vendor_name?: string | null;
            /** Vendor Gstin */
            vendor_gstin?: string | null;
            /** Transaction Date */
            transaction_date?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Subtotal */
            subtotal?: number | null;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total Amount */
            total_amount?: number | null;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Payment Method */
            payment_method?: string | null;
            /** Cgst Amount */
            cgst_amount?: number | null;
            /** Sgst Amount */
            sgst_amount?: number | null;
            /** Igst Amount */
            igst_amount?: number | null;
            /** Hsn Sac Code */
            hsn_sac_code?: string | null;
            /** Irn */
            irn?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["LineItemExtraction"][];
            /** Confidence Score */
            confidence_score: number;
            /** Raw Response */
            raw_response?: string | null;
        };
        /**
         * ExtractionValidationResult
         * @description Validation result for extracted data.
         */
        ExtractionValidationResult: {
            /** Is Valid */
            is_valid: boolean;
            /** Errors */
            errors?: string[];
            /** Warnings */
            warnings?: string[];
            /**
             * Confidence Adjustment
             * @default 0
             */
            confidence_adjustment: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LineItemExtraction
         * @description Extracted line item.
         */
        LineItemExtraction: {
            /** Description */
            description: string;
            /** Quantity */
            quantity?: number | null;
            /** Unit Price */
            unit_price?: number | null;
            /** Amount */
            amount: number;
            /** Tax Amount */
            tax_amount?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OCRJobListResponse
         * @description Paginated OCR job list.
         */
        OCRJobListResponse: {
            /** Items */
            items: components["schemas"]["OCRJobStatus"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * OCRJobStatus
         * @description OCR job status response.
         */
        OCRJobStatus: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Event Id */
            source_event_id: string | null;
            /** Status */
            status: string;
            result: components["schemas"]["OCRResult"] | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * OCRLine
         * @description Single line of OCR output.
         */
        OCRLine: {
            /** Text */
            text: string;
            /** Confidence */
            confidence: number;
            /** Bbox */
            bbox: {
                [key: string]: number;
            };
            /** Line Num */
            line_num: number;
            /** Block Num */
            block_num: number;
        };
        /**
         * OCRProcessRequest
         * @description Request to process OCR on evidence.
         */
        OCRProcessRequest: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Language */
            language?: string | null;
            /** Preprocessing Options */
            preprocessing_options?: Record<string, never> | null;
        };
        /**
         * OCRProcessResponse
         * @description Response after OCR processing.
         */
        OCRProcessResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * OCRResult
         * @description OCR extraction result.
         */
        OCRResult: {
            /** Full Text */
            full_text: string;
            /** Avg Confidence */
            avg_confidence: number;
            /** Lines */
            lines: components["schemas"]["OCRLine"][];
            /** Word Count */
            word_count: number;
        };
        /**
         * PresignedUrlRequest
         * @description Request for presigned URL.
         */
        PresignedUrlRequest: {
            /** Object Name */
            object_name: string;
            /**
             * Expires In Seconds
             * @default 3600
             */
            expires_in_seconds: number;
            /**
             * Method
             * @default GET
             */
            method: string;
        };
        /**
         * PresignedUrlResponse
         * @description Presigned URL response.
         */
        PresignedUrlResponse: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Method */
            method: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /**
             * Status
             * @default active
             */
            status: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Status */
            status: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * StageActionRequest
         * @description Request to approve/reject staged expense.
         */
        StageActionRequest: {
            /** Action */
            action: string;
            /**
             * Reviewer Id
             * Format: uuid
             */
            reviewer_id: string;
            /** Notes */
            notes?: string | null;
            /** Corrections */
            corrections?: Record<string, never> | null;
        };
        /**
         * StageActionResponse
         * @description Response after stage action.
         */
        StageActionResponse: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /** Action */
            action: string;
            /** New Status */
            new_status: string;
            /** Message */
            message: string;
        };
        /**
         * StagedExpenseDetail
         * @description Detailed staged expense for review UI.
         */
        StagedExpenseDetail: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Project Name */
            project_name?: string | null;
            /** Source Event Id */
            source_event_id?: string | null;
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Vendor Name */
            vendor_name?: string | null;
            /** Vendor Gstin */
            vendor_gstin?: string | null;
            /** Transaction Date */
            transaction_date?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Subtotal */
            subtotal?: number | null;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total Amount */
            total_amount?: number | null;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Payment Method */
            payment_method?: string | null;
            /** Cgst Amount */
            cgst_amount?: number | null;
            /** Sgst Amount */
            sgst_amount?: number | null;
            /** Igst Amount */
            igst_amount?: number | null;
            /** Hsn Sac Code */
            hsn_sac_code?: string | null;
            /** Irn */
            irn?: string | null;
            /** Confidence Score */
            confidence_score: number;
            /** Extraction Result */
            extraction_result?: Record<string, never> | null;
            /** Validation Errors */
            validation_errors?: string[];
            /** Validation Warnings */
            validation_warnings?: string[];
            /** Line Items */
            line_items?: Record<string, never>[];
            /**
             * Staged At
             * Format: date-time
             */
            staged_at: string;
            /** Staged By */
            staged_by?: string | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Review Notes */
            review_notes?: string | null;
        };
        /**
         * StagedExpenseItem
         * @description Single staged expense item for review.
         */
        StagedExpenseItem: {
            /**
             * Expense Id
             * Format: uuid
             */
            expense_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Vendor Gstin */
            vendor_gstin?: string | null;
            /** Transaction Date */
            transaction_date?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Subtotal */
            subtotal?: number | null;
            /** Tax Amount */
            tax_amount?: number | null;
            /** Total Amount */
            total_amount?: number | null;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Payment Method */
            payment_method?: string | null;
            /** Confidence Score */
            confidence_score: number;
            /** Extraction Result */
            extraction_result?: Record<string, never> | null;
            /** Validation Errors */
            validation_errors?: string[];
            /** Validation Warnings */
            validation_warnings?: string[];
        };
        /**
         * StagedListResponse
         * @description Paginated staged expenses list.
         */
        StagedListResponse: {
            /** Items */
            items: components["schemas"]["StagedExpenseDetail"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * StagingRequest
         * @description Request to stage expenses for review.
         */
        StagingRequest: {
            /** Expense Ids */
            expense_ids: string[];
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * StagingResponse
         * @description Response after staging expenses.
         */
        StagingResponse: {
            /** Staged Count */
            staged_count: number;
            /** Message */
            message: string;
            /** Staged Expenses */
            staged_expenses: components["schemas"]["StagedExpenseItem"][];
        };
        /**
         * StagingStats
         * @description Staging statistics.
         */
        StagingStats: {
            /** Pending Review */
            pending_review: number;
            /** Approved */
            approved: number;
            /** Rejected */
            rejected: number;
            /** Changes Requested */
            changes_requested: number;
            /** Total Staged */
            total_staged: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VendorResponse */
        VendorResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Gstin */
            gstin?: string | null;
            /** Phone */
            phone?: string | null;
            /** Notes */
            notes?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_only_endpoint_api_v1_auth_admin_only_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pm_or_admin_endpoint_api_v1_auth_pm_or_admin_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_vs_actual_api_v1_projects__project_id__budget_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetVsActualResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_budget_api_v1_projects__project_id__budget_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budgets_api_v1_projects__project_id__budgets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                vendor_id?: string | null;
                category_id?: string | null;
                status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_api_v1_expenses__expense_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_expense_api_v1_expenses__expense_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_evidence_api_v1_evidence_upload_post: {
        parameters: {
            query: {
                expense_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_evidence_api_v1_evidence_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evidence_api_v1_evidence__evidence_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_by_expense_api_v1_evidence_expense__expense_id__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presigned_url_api_v1_evidence_presigned_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ocr_processing_api_v1_ocr_process_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OCRProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OCRProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ocr_job_api_v1_ocr_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OCRJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ocr_job_api_v1_ocr_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ocr_jobs_api_v1_ocr_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status_filter?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OCRJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_ocr_job_api_v1_ocr_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OCRJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_extraction_api_v1_extraction_process_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_sync_api_v1_extraction_process_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extraction_job_api_v1_extraction_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_extraction_job_api_v1_extraction_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_extraction_jobs_api_v1_extraction_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status_filter?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_extraction_job_api_v1_extraction_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_extraction_api_v1_extraction_validate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_expenses_api_v1_staging_stage_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StagingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staged_expenses_api_v1_staging_expenses_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status_filter?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staged_expense_api_v1_staging_expenses__expense_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedExpenseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_stage_action_api_v1_staging_expenses__expense_id__action_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staging_stats_api_v1_staging_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
