"""add full schema: vendors, categories, source_events, audit, receipts, expenses, payments, reconciliation, ledger, projects, budgets, processing_jobs, integration_configs

Revision ID: 2104e97b75b2
Revises: e31df842f0c4
Create Date: 2026-09-20 22:02:20.992853

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2104e97b75b2'
down_revision: str | None = 'e31df842f0c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.String(length=5000), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('source_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Enum('WHATSAPP', 'SMS_UPI', 'MANUAL', name='source_type', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_events_external_id'), 'source_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_events_idempotency_key'), 'source_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_source_events_source'), 'source_events', ['source'], unique=False)
    op.create_index('ix_source_events_source_external_id', 'source_events', ['source', 'external_id'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['causation_id'], ['audit_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_causation_id'), 'audit_events', ['causation_id'], unique=False)
    op.create_index('ix_audit_events_correlation_id', 'audit_events', ['correlation_id'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payee_raw_text', sa.String(length=255), nullable=False),
    sa.Column('upi_reference', sa.String(length=64), nullable=True),
    sa.Column('bank_reference', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'OTHER', name='payment_method', native_enum=False), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.String(length=2000), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_events_amount_occurred', 'payment_events', ['amount', 'occurred_at'], unique=False)
    op.create_index('ix_payment_events_bank_ref', 'payment_events', ['bank_reference'], unique=False)
    op.create_index(op.f('ix_payment_events_bank_reference'), 'payment_events', ['bank_reference'], unique=False)
    op.create_index(op.f('ix_payment_events_idempotency_key'), 'payment_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_events_occurred_at'), 'payment_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_payment_events_source_event_id'), 'payment_events', ['source_event_id'], unique=False)
    op.create_index('ix_payment_events_upi_ref', 'payment_events', ['upi_reference'], unique=False)
    op.create_index(op.f('ix_payment_events_upi_reference'), 'payment_events', ['upi_reference'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_type', sa.Enum('MEDIA_DOWNLOAD', 'OCR', 'LLM_EXTRACT', 'RECONCILE', 'NOTIFY_WHATSAPP', name='job_type', native_enum=False), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', name='job_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_source_event_id'), 'processing_jobs', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_type_status', 'processing_jobs', ['job_type', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'OTHER', name='payment_method', native_enum=False), nullable=False),
    sa.Column('gstin_supplier', sa.String(length=15), nullable=True),
    sa.Column('hsn_sac_code', sa.String(length=20), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('irn', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('extraction_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('RECEIVED', 'VALIDATED', 'PROCESSING', 'EXTRACTED', 'NEEDS_CONFIRMATION', 'STAGED', 'RECONCILING', 'RECONCILED', 'POSTED', 'FAILED', 'REJECTED', 'UNMATCHED', 'AMBIGUOUS', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('source_audit_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_audit_event_id'], ['audit_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_lifecycle_status'), 'expenses', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_expenses_project_id'), 'expenses', ['project_id'], unique=False)
    op.create_index('ix_expenses_project_status_date', 'expenses', ['project_id', 'lifecycle_status', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_expenses_source_event_id'), 'expenses', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_expenses_transaction_date'), 'expenses', ['transaction_date'], unique=False)
    op.create_index('ix_expenses_vendor_date', 'expenses', ['vendor_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_expenses_vendor_id'), 'expenses', ['vendor_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('processing_job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_attempts_processing_job_id'), 'job_attempts', ['processing_job_id'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'EXPENSE', 'LIABILITY', name='account_type', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_accounts_project_id'), 'ledger_accounts', ['project_id'], unique=False)
    op.create_index('ix_ledger_accounts_project_type', 'ledger_accounts', ['project_id', 'account_type'], unique=False)
    op.create_table('project_budgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_budgets_category_effective', 'project_budgets', ['category_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_project_budgets_category_id'), 'project_budgets', ['category_id'], unique=False)
    op.create_index('ix_project_budgets_project_effective', 'project_budgets', ['project_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=False)
    op.create_table('expense_line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_line_items_expense_id'), 'expense_line_items', ['expense_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ledger_account_id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entry_type', native_enum=False), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_audit_event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_audit_event_id'], ['audit_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_entries_account_posted', 'ledger_entries', ['ledger_account_id', 'posted_at'], unique=False)
    op.create_index('ix_ledger_entries_expense', 'ledger_entries', ['expense_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_expense_id'), 'ledger_entries', ['expense_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_ledger_account_id'), 'ledger_entries', ['ledger_account_id'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('payment_event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', 'MANUALLY_RESOLVED', name='reconciliation_status', native_enum=False), nullable=False),
    sa.Column('match_basis', sa.Enum('REFERENCE', 'SCORED', 'MANUAL', name='match_basis', native_enum=False), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_expense_id'), 'reconciliation_records', ['expense_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_payment_event_id'), 'reconciliation_records', ['payment_event_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_status'), 'reconciliation_records', ['status'], unique=False)
    op.create_index('ix_reconciliation_status_expense', 'reconciliation_records', ['status', 'expense_id'], unique=False)
    op.create_index('ix_reconciliation_status_payment', 'reconciliation_records', ['status', 'payment_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_status_payment', table_name='reconciliation_records')
    op.drop_index('ix_reconciliation_status_expense', table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_status'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_payment_event_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_expense_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_ledger_entries_ledger_account_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_expense_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_expense', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account_posted', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_expense_line_items_expense_id'), table_name='expense_line_items')
    op.drop_table('expense_line_items')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_index('ix_project_budgets_project_effective', table_name='project_budgets')
    op.drop_index(op.f('ix_project_budgets_category_id'), table_name='project_budgets')
    op.drop_index('ix_project_budgets_category_effective', table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index('ix_ledger_accounts_project_type', table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_project_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index(op.f('ix_job_attempts_processing_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_expenses_vendor_id'), table_name='expenses')
    op.drop_index('ix_expenses_vendor_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_transaction_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_source_event_id'), table_name='expenses')
    op.drop_index('ix_expenses_project_status_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_project_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_lifecycle_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_processing_jobs_type_status', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_source_event_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_payment_events_upi_reference'), table_name='payment_events')
    op.drop_index('ix_payment_events_upi_ref', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_source_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_occurred_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_idempotency_key'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_bank_reference'), table_name='payment_events')
    op.drop_index('ix_payment_events_bank_ref', table_name='payment_events')
    op.drop_index('ix_payment_events_amount_occurred', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_correlation_id', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_causation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_source_events_source_external_id', table_name='source_events')
    op.drop_index(op.f('ix_source_events_source'), table_name='source_events')
    op.drop_index(op.f('ix_source_events_idempotency_key'), table_name='source_events')
    op.drop_index(op.f('ix_source_events_external_id'), table_name='source_events')
    op.drop_table('source_events')
    op.drop_table('integration_configs')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
