"""make source_audit_event_id nullable

Revision ID: 3c93f15dc297
Revises: 701ca8e4734d
Create Date: 2026-09-21 05:43:29.453458

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c93f15dc297'
down_revision: str | None = '701ca8e4734d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'source_audit_event_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'source_audit_event_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###