"""add user and role models

Revision ID: e31df842f0c4
Revises: 20260920_120501
Create Date: 2026-09-20 09:00:34.184942

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e31df842f0c4'
down_revision: str | None = '20260920_120501'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    # ### end Alembic commands ###
